import 'package:flutter_riverpod/flutter_riverpod.dart';

import '../models/compliance_models.dart';
import '../repositories/compliance_repository.dart';
import 'network_providers.dart';

final complianceRepositoryProvider = Provider<ComplianceRepository>((ref) {
  return ComplianceRepository(ref.watch(dioProvider));
});

final complianceProductsProvider = FutureProvider<List<ComplianceProduct>>((ref) async {
  final repo = ref.watch(complianceRepositoryProvider);
  try {
    final list = await repo.getComplianceProducts();
    if (list.isNotEmpty) return list;
  } catch (_) {}
  return const [
    ComplianceProduct(
      id: 'smartwatch',
      name: 'Smart Watch',
      category: 'CRS Scheme (Electronics)',
      description: 'Wearable electronic devices with Bluetooth/WiFi & sensors under IS 13252 (Part 1).',
      standardCode: 'IS 13252 (Part 1) : 2010',
    ),
    ComplianceProduct(
      id: 'earbuds',
      name: 'Wireless Earbuds',
      category: 'CRS Scheme (Audio/Wireless)',
      description: 'TWS In-Ear headphones & rechargeable Lithium battery compliance under IS 616.',
      standardCode: 'IS 616 : 2017 & IS 16046',
    ),
    ComplianceProduct(
      id: 'bluetooth_speaker',
      name: 'Bluetooth Speaker',
      category: 'CRS Scheme (Audio Equipment)',
      description: 'Portable mains & battery-powered loudspeaker systems under Safety Standards.',
      standardCode: 'IS 616 : 2017',
    ),
    ComplianceProduct(
      id: 'led_lighting',
      name: 'LED Lighting',
      category: 'Scheme I (ISI Mark)',
      description: 'Self-ballasted LED lamps & luminaire safety requirements.',
      standardCode: 'IS 16102 (Part 1) : 2012',
    ),
  ];
});

final selectedComplianceProductIdProvider = StateProvider<String>((ref) => 'smartwatch');

final complianceJourneyFamilyProvider = FutureProvider.family<ComplianceProductJourney, String>((ref, productId) async {
  final repo = ref.watch(complianceRepositoryProvider);
  try {
    return await repo.getComplianceJourney(productId);
  } catch (_) {
    return _sampleJourney(productId);
  }
});

ComplianceProductJourney _sampleJourney(String productId) {
  final String productName = switch (productId) {
    'smartwatch' => 'Smart Watch',
    'earbuds' => 'Wireless Earbuds',
    'bluetooth_speaker' => 'Bluetooth Speaker',
    _ => 'LED Lighting Product',
  };

  final String code = switch (productId) {
    'smartwatch' => 'IS 13252 (Part 1)',
    'earbuds' => 'IS 616 & IS 16046',
    'bluetooth_speaker' => 'IS 616 : 2017',
    _ => 'IS 16102 (Part 1)',
  };

  return ComplianceProductJourney(
    productId: productId,
    productName: productName,
    category: 'Compulsory Registration Scheme (CRS)',
    overallProgress: 0.60,
    steps: [
      ComplianceTimelineStep(
        stepNumber: 1,
        title: 'Product Classification',
        subtitle: 'Identified under Electronic Goods Order',
        description: 'Confirmed as "$productName" under Compulsory Registration Scheme.',
        status: StepStatus.completed,
        standardCode: code,
      ),
      ComplianceTimelineStep(
        stepNumber: 2,
        title: 'Applicable Standard Match: $code',
        subtitle: 'Safety & Battery Compliance Requirements',
        description: 'Matched with official Indian Standard specifications for safety & battery testing.',
        status: StepStatus.completed,
        standardCode: code,
      ),
      ComplianceTimelineStep(
        stepNumber: 3,
        title: 'Sample Testing in BIS Recognized Lab',
        subtitle: 'Conformity report generation',
        description: 'Test report generated by a recognized laboratory in India.',
        status: StepStatus.inProgress,
        standardCode: code,
      ),
      ComplianceTimelineStep(
        stepNumber: 4,
        title: 'CRS Online Application Submission',
        subtitle: 'Portal registration & AIR nomination',
        description: 'Filing application on the BIS portal with laboratory report attached.',
        status: StepStatus.pending,
      ),
      ComplianceTimelineStep(
        stepNumber: 5,
        title: 'Grant of License & R-Number',
        subtitle: 'Product Marking & Standard Logo',
        description: 'Issuance of unique R-Number to be printed on product packaging and e-labels.',
        status: StepStatus.pending,
      ),
    ],
  );
}
